version: '3'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgres://varunpandey:boombamboom@db:5432/BaazaarAPI
    depends_on:
      - db
    volumes:
      - .:/app
  db:
    image: postgres
    environment:
      POSTGRES_DB: BaazaarAPI
      POSTGRES_USER: varunpandey
      POSTGRES_PASSWORD: boombamboom
