# Generated by Django 4.2.10 on 2024-03-01 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_userpayment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserPayment',
        ),
    ]
